MewsSystems/gitbook-channel-manager-api

channel-manager-api.md
=> Change emphasis to H5

mews-api.md
Minor style changes & added the new PCI-Proxy push endpoints.
=> Updated reservation delivery process

mews-api.md
Add additional supported country code format to country and nationality fields.
=> Add additional supported country code format

mews-api.md
Updated processGroup part to have multi-room reservations sent in one request. Updated modify reservation part to have chm send us same chm id with modification. Updated XML with future dates.
=> Update processGroup requirements

channel-manager-api.md
Sorry, I had to fix inconsistent formatting in VisualCode, so the entire thing looks it was formatted...
=> changed formatting. No info updates

mews-api.md
Request example for processGroup is missing :
=> Request example missing :

mews-api.md
added a line that null is not accepted
=> Extras in processGroup

mews-api.md
Added that CVV cant be 000. Improved setInventory explanation
=> cvv and setInventory

general-remarks.md
=> error code 2

mews-api.md
Striked them thru as not all supported in Commander
=> Space classifications

mews-api.md
Added an explanation to the extras from and to format
=> Extra date format

mews-api.md
As per - https://mews.myjetbrains.com/youtrack/issue/RND-36887
=> Add loyalty code to documentation

changelog.md
Don't merge it until pr#73 is merged.
=> new errors and loyalty.

channels.md
=> channel update

general-remarks.md
=> Changed HTTP wording to HTTPS

mews-api.md
Fixed reference from app.* to api.*.
=> Fixed links in mews-api

changelog/README.md, guidelines/responses.md
Ref. https://app.asana.com/0/1201871773388036/1201941712959900/f
=> further refinements to error responses

changelog/changelog2022.md, mews-operations/reservations.md
* Added Source definition in Process Group
* Deprecated Channel in Process Group
=> Added Source definition in Process Group

SUMMARY.md, changelog/README.md, changelog/changelog2023.md, mews-operations/reservations.md
* Added Age Category Code in Process Group (documentation only)
* Corrected last changelog entry (change was created in Dec 2023 but merged in Jan 2024)
* Rolled over 2023 changelog and started new page for 2024
=> Age Category Code in Process Group

.gitignore, changelog/README.md, channel-manager-operations/inventory.md, mews-operations/reservations.md
- Fixed bug about restrictions - invalid value for `states` for closed
- Added `LoyaltyInfo` to `Customer`
=> [docs] Customer.LoyaltyInfo, Restriction fix

changelog/README.md, channel-manager-operations/availabilityBlock.md, channel-manager-operations/inventory.md, mews-operations/reservations.md
Part of https://mews.atlassian.net/browse/CON-1854
=> Dates specified to be included or excluded

changelog/README.md, deprecations/README.md, mews-operations/configuration.md
=> Obsolete paymentType

SUMMARY.md, changelog/README.md
* Removed deleted 'Integration process' page from SUMMARY.md
* Corrected Changelog for Restrictions entry from 1st August to 11th September
=> Minor corrections

.github/workflows/add-label.yaml
=> Auto labeling added

changelog/README.md, channel-manager-operations/availabilityBlock.md, deprecations/README.md, mews-operations/availabilityBlock.md
https://mews.atlassian.net/browse/CON-4154: update documentation
=> Con 4154: Release strategy for block synchronization and block processing - update document

changelog/README.md, your-journey/README.md, your-journey/certification.md
* Minor refinements to `Your integration journey` and `Certification` pages, following feedback from David Parizek
=> minor refinements to integration journey and certification

.github/CODEOWNERS
* Summarise the changes here in bullet points
=> Set codeowners to connectivity-contract-owners
